import Analyzer from "./analysis/Analyzer.js";

const analyzer = new Analyzer();

const textToTest = [
    "The Shawshank Redemption",
    "The Godfather",
    "The Dark Knight",
    "Pulp Fiction",
    "The Lord of the Rings: The Return of the King",
    "Forrest Gump",
    "Inception",
    "Fight Club",
    "The Matrix",
    "Goodfellas",
    "Interstellar",
    "Se7en",
    "The Silence of the Lambs",
    "Saving Private Ryan",
    "The Green Mile",
    "Gladiator",
    "The Prestige",
    "The Lion King",
    "Whiplash",
    "The Departed",
    "Django Unchained",
    "The Social Network",
    "Parasite",
    "Avengers: Endgame",
    "Avengers: Infinity War",
    "Spider-Man: No Way Home",
    "Joker",
    "Titanic",
    "Jurassic Park",
    "Star Wars: A New Hope",
    "Star Wars: The Empire Strikes Back",
    "Return of the Jedi",
    "Rogue One: A Star Wars Story",
    "Mad Max: Fury Road",
    "Blade Runner",
    "Blade Runner 2049",
    "The Terminator",
    "Terminator 2: Judgment Day",
    "Alien",
    "Aliens",
    "The Exorcist",
    "The Shining",
    "Get Out",
    "Hereditary",
    "A Quiet Place",
    "The Conjuring",
    "It",
    "The Batman",
    "Batman Begins",
    "The Dark Knight Rises",
    "Iron Man",
    "Captain America: The Winter Soldier",
    "Black Panther",
    "Doctor Strange",
    "Guardians of the Galaxy",
    "Thor: Ragnarok",
    "Deadpool",
    "Logan",
    "X-Men: Days of Future Past",
    "The Hunger Games",
    "Catching Fire",
    "Harry Potter and the Sorcerer's Stone",
    "Harry Potter and the Prisoner of Azkaban",
    "Harry Potter and the Deathly Hallows",
    "Fantastic Beasts and Where to Find Them",
    "The Hobbit: An Unexpected Journey",
    "The Hobbit: The Desolation of Smaug",
    "The Hobbit: The Battle of the Five Armies",
    "Toy Story",
    "Toy Story 2",
    "Toy Story 3",
    "Finding Nemo",
    "Finding Dory",
    "Inside Out",
    "Coco",
    "Up",
    "Wall-E",
    "Ratatouille",
    "Monsters, Inc.",
    "Frozen",
    "Frozen II",
    "Moana",
    "Zootopia",
    "Shrek",
    "Shrek 2",
    "Kung Fu Panda",
    "How to Train Your Dragon",
    "The Incredibles",
    "The Incredibles 2",
    "La La Land",
    "The Grand Budapest Hotel",
    "No Country for Old Men",
    "There Will Be Blood",
    "The Wolf of Wall Street",
    "The Revenant",
    "Once Upon a Time in Hollywood",
    "Knives Out",
    "The Irishman",
    "Oppenheimer"
];

for (const text of textToTest) {
    console.log(`Original: "${text}"`);
    console.log(`Analyzed:`, analyzer.analyze(text));
    console.log('---');
}
